import { Barlow_Condensed } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Layout/Navbar";

const barlowCondensed = Barlow_Condensed({
  variable: "--font-barlow-condensed",
  subsets: ["latin"],
  weight: ["400", "700"], // Add the weights you need
});

export const metadata = {
  title: "A-Line",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${barlowCondensed.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}